"""notice of non selection

Revision ID: 11dd09c50161
Revises: 4b8b699a4d28
Create Date: 2015-06-28 22:44:02.031358

"""

# revision identifiers, used by Alembic.
revision = '11dd09c50161'
down_revision = '4b8b699a4d28'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('non_selection_notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'product', sa.Column('original_deadline', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'product', 'original_deadline')
    op.drop_table('non_selection_notice')
    ### end Alembic commands ###
