"""creates notification table

Revision ID: 1f43fb8f5121
Revises: 48d0bf680734
Create Date: 2015-06-18 06:44:24.923010

"""

# revision identifiers, used by Alembic.
revision = '1f43fb8f5121'
down_revision = '48d0bf680734'

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects.postgresql import ENUM

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sent', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('confirmed', 'pending', 'declined', name='notification_statuses'), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('cn_proposal_id', sa.Integer(), nullable=True),
    sa.Column('sn_slot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['cn_proposal_id'], ['proposal.id'], ),
    sa.ForeignKeyConstraint(['sn_slot_id'], ['slot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    ENUM(name="notification_statuses").drop(op.get_bind(), checkfirst=False)
    ### end Alembic commands ###
