"""visitor table and prefix column for badge

Revision ID: 1fc7d636675a
Revises: 50726805d9a6
Create Date: 2015-07-06 14:51:13.299783

"""

# revision identifiers, used by Alembic.
revision = '1fc7d636675a'
down_revision = '50726805d9a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'badge', sa.Column('visitor_id', sa.Integer(), nullable=True))
    op.add_column(u'badge', sa.Column('prefix',     sa.Text(), nullable=True))
    op.create_foreign_key(None, 'badge', 'visitor', ['visitor_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'badge', type_='foreignkey')
    op.drop_column(u'badge', 'visitor_id')
    op.drop_table('visitor')
    ### end Alembic commands ###
