"""added personal information

Revision ID: 24576c9505ad
Revises: 3bfd530b7234
Create Date: 2015-02-03 02:07:07.682968

"""

# revision identifiers, used by Alembic.
revision = '24576c9505ad'
down_revision = '3bfd530b7234'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('city', sa.Text(), nullable=True))
    op.add_column('account', sa.Column('country', sa.Text(), nullable=True))
    op.add_column('account', sa.Column('organization', sa.Text(), nullable=True))
    op.add_column('account', sa.Column('phone', sa.Text(), nullable=True))
    op.add_column('account', sa.Column('resume', sa.Text(), nullable=True))
    op.add_column('account', sa.Column('state', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'state')
    op.drop_column('account', 'resume')
    op.drop_column('account', 'phone')
    op.drop_column('account', 'organization')
    op.drop_column('account', 'country')
    op.drop_column('account', 'city')
    ### end Alembic commands ###
