"""added_description_payment

Revision ID: 2a666d5ade85
Revises: 3b6b766a840d
Create Date: 2015-07-04 15:56:10.489321

"""

# revision identifiers, used by Alembic.
revision = '2a666d5ade85'
down_revision = '3b6b766a840d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('description', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'description')
    ### end Alembic commands ###
