"""printer copies and job id

Revision ID: 2cd344823c39
Revises: 5301d6bd6e81
Create Date: 2015-07-03 16:50:57.524319

"""

# revision identifiers, used by Alembic.
revision = '2cd344823c39'
down_revision = '5301d6bd6e81'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badge', sa.Column('copies', sa.Integer(), nullable=True))
    op.add_column('badge', sa.Column('job_id', sa.Text(), nullable=True))
    op.add_column('badge', sa.Column('printer', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('badge', 'printer')
    op.drop_column('badge', 'job_id')
    op.drop_column('badge', 'copies')
    ### end Alembic commands ###
