"""added payment transition table

Revision ID: 2d01630380b2
Revises: 622aeeebb80
Create Date: 2015-03-16 05:40:49.835220

"""

# revision identifiers, used by Alembic.
revision = '2d01630380b2'
down_revision = '622aeeebb80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('old_status', sa.Text(), nullable=True),
    sa.Column('new_status', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transition')
    ### end Alembic commands ###
