"""empty message

Revision ID: 315c3b64309b
Revises: None
Create Date: 2015-01-04 00:02:42.901241

"""

# revision identifiers, used by Alembic.
revision = '315c3b64309b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_authorization', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('level', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposal')
    ### end Alembic commands ###
