"""creates caravan purchases

Revision ID: 324632da9bd3
Revises: 2624c849d8be
Create Date: 2015-04-13 01:40:15.123190

"""

# revision identifiers, used by Alembic.
revision = '324632da9bd3'
down_revision = '2624c849d8be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('cr_caravan_id', sa.Integer(), nullable=True))
    op.add_column('purchase', sa.Column('kind', sa.Text(), server_default='single', nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'kind')
    op.drop_column('purchase', 'cr_caravan_id')
    ### end Alembic commands ###
