"""removed_corporate_employee_account_relationship

Revision ID: 34d7989605a9
Revises: 2a666d5ade85
Create Date: 2015-07-05 15:14:32.784433

"""

# revision identifiers, used by Alembic.
revision = '34d7989605a9'
down_revision = '2a666d5ade85'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'corporate', 'account', type_='foreignkey')
    op.drop_column('account', 'cr_corporate_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('cr_corporate_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'corporate', 'account', 'corporate', ['cr_corporate_id'], ['id'])
    ### end Alembic commands ###
