"""proposal is owned by account

Revision ID: 3629377a0cc2
Revises: 24576c9505ad
Create Date: 2015-02-03 02:46:50.158183

"""

# revision identifiers, used by Alembic.
revision = '3629377a0cc2'
down_revision = '24576c9505ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key('proposal_owner_id_fkey', 'proposal', 'account', ['owner_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('proposal_owner_id_fkey', 'proposal', type_='foreignkey')
    op.drop_column('proposal', 'owner_id')
    ### end Alembic commands ###
