"""ip address column name fixed

Revision ID: 39a9a9acc78f
Revises: 1802fdfd2408
Create Date: 2015-07-03 14:55:23.587408

"""

# revision identifiers, used by Alembic.
revision = '39a9a9acc78f'
down_revision = '1802fdfd2408'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transition', sa.Column('ca_ip_address', sa.String(), nullable=True))
    op.drop_column('transition', 'ip_addres')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transition', sa.Column('ip_addres', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transition', 'ca_ip_address')
    ### end Alembic commands ###
