"""ensures_email_unique

Revision ID: 3bfd530b7234
Revises: 3d0cd981882e
Create Date: 2015-01-13 02:27:25.602352

"""

# revision identifiers, used by Alembic.
revision = '3bfd530b7234'
down_revision = '3d0cd981882e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("account_email_UK", "account", ["email"])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
