"""created and last_update columns for proposal and account

Revision ID: 3c300f7bbb2
Revises: 592d911e8679
Create Date: 2015-02-07 02:34:22.966763

"""

# revision identifiers, used by Alembic.
revision = '3c300f7bbb2'
down_revision = '592d911e8679'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('account', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('proposal', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('proposal', sa.Column('last_updated', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal', 'last_updated')
    op.drop_column('proposal', 'created')
    op.drop_column('account', 'last_updated')
    op.drop_column('account', 'created')
    ### end Alembic commands ###
