"""boleto columns added to payment and transition tables

Revision ID: 3c531310f2d0
Revises: 2e8077fe0870
Create Date: 2015-03-23 02:24:13.928437

"""

# revision identifiers, used by Alembic.
revision = '3c531310f2d0'
down_revision = '2e8077fe0870'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('bo_document_hash', sa.String(length=32), nullable=True))
    op.add_column('payment', sa.Column('bo_due_date', sa.Date(), nullable=True))
    op.add_column('payment', sa.Column('bo_our_number', sa.Integer(), nullable=True))
    op.add_column('transition', sa.Column('bo_batch_file', sa.Text(), nullable=True))
    op.add_column('transition', sa.Column('bo_batch_line', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transition', 'bo_batch_line')
    op.drop_column('transition', 'bo_batch_file')
    op.drop_column('payment', 'bo_our_number')
    op.drop_column('payment', 'bo_due_date')
    op.drop_column('payment', 'bo_document_hash')
    ### end Alembic commands ###
