"""added account table

Revision ID: 3d0cd981882e
Revises: 564d391c174c
Create Date: 2015-01-12 16:17:25.396272

"""

# revision identifiers, used by Alembic.
revision = '3d0cd981882e'
down_revision = '564d391c174c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('user', 'operator', 'admin', name="account_roles"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    ### end Alembic commands ###
