"""reset password table; added foreign key from purchase to caravan that was missing for some reason

Revision ID: 3f7a730da6dc
Revises: 324632da9bd3
Create Date: 2015-04-19 21:35:26.913114

"""

# revision identifiers, used by Alembic.
revision = '3f7a730da6dc'
down_revision = '324632da9bd3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_password',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('spent', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'purchase', 'caravan', ['cr_caravan_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.drop_table('reset_password')
    ### end Alembic commands ###
