"""created product and purchase table

Revision ID: 3f7cba6f0a37
Revises: 16b1659c8e
Create Date: 2015-03-03 02:07:59.156974

"""

# revision identifiers, used by Alembic.
revision = '3f7cba6f0a37'
down_revision = '16b1659c8e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('kind', sa.Enum('ticket', 'swag', name="product_kinds"), nullable=True),
        sa.Column('category', sa.Text(), nullable=True),
        sa.Column('expiration', sa.DateTime(), nullable=True),
        sa.Column('public', sa.Boolean(), nullable=True),
        sa.Column('price', sa.Numeric(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=True),
        sa.Column('customer_id', sa.Integer(), nullable=True),
        sa.Column('status', sa.Text(), nullable=True),
        sa.Column('buyer_type', sa.Enum('person', 'company', 'government', name="buyer_types"), nullable=False),
        sa.Column('buyer_name', sa.Text(), nullable=False),
        sa.Column('buyer_document', sa.Text(), nullable=False),
        sa.Column('buyer_contact', sa.Text(), nullable=False),
        sa.Column('buyer_address', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['account.id'], ),
        sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase')
    op.drop_table('product')
    ENUM(name="product_kinds").drop(op.get_bind(), checkfirst=False)
    ENUM(name="buyer_types").drop(op.get_bind(), checkfirst=False)
    ### end Alembic commands ###
