"""mode column for cash

Revision ID: 465d0dff297
Revises: 10af42e8f6f4
Create Date: 2015-07-07 18:14:02.956635

"""

# revision identifiers, used by Alembic.
revision = '465d0dff297'
down_revision = '10af42e8f6f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transition', sa.Column('ca_mode', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transition', 'ca_mode')
    ### end Alembic commands ###
