"""certificate table

Revision ID: 49dd83ecaff7
Revises: e95413a8654
Create Date: 2015-07-24 03:58:53.756849

"""

# revision identifiers, used by Alembic.
revision = '49dd83ecaff7'
down_revision = 'e95413a8654'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('hash_code', sa.String(length=10), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('sc_talk_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['sc_talk_id'], ['proposal.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['purchase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificate')
    ### end Alembic commands ###
