"""proposal status column

Revision ID: 4b372eb156d
Revises: 317c258a7219
Create Date: 2015-06-09 02:47:06.761572

"""

# revision identifiers, used by Alembic.
revision = '4b372eb156d'
down_revision = '317c258a7219'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('status', sa.Text(), server_default='proposal', nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal', 'status')
    ### end Alembic commands ###
