"""added_corporate_tables

Revision ID: 4eca52589479
Revises: 1802fdfd2408
Create Date: 2015-07-03 12:03:31.750204

"""

# revision identifiers, used by Alembic.
revision = '4eca52589479'
down_revision = '1802fdfd2408'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('badge_name', sa.Text(), nullable=True),
    sa.Column('document', sa.Text(), nullable=True),
    sa.Column('address_street', sa.Text(), nullable=True),
    sa.Column('address_number', sa.Text(), nullable=True),
    sa.Column('address_extra', sa.Text(), nullable=True),
    sa.Column('address_district', sa.Text(), nullable=True),
    sa.Column('address_city', sa.Text(), nullable=True),
    sa.Column('address_state', sa.Text(), nullable=True),
    sa.Column('address_zipcode', sa.Text(), nullable=True),
    sa.Column('incharge_name', sa.Text(), nullable=True),
    sa.Column('incharge_email', sa.Text(), nullable=True),
    sa.Column('incharge_phone_1', sa.Text(), nullable=True),
    sa.Column('incharge_phone_2', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'account', sa.Column('badge_name', sa.Text(), nullable=True))
    op.add_column(u'account', sa.Column('cr_corporate_id', sa.Integer(), nullable=True))
    op.create_foreign_key('corporate', 'account', 'corporate', ['cr_corporate_id'], ['id'])
    op.add_column(u'purchase', sa.Column('cr_corporate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase', 'corporate', ['cr_corporate_id'], ['id'])
    op.add_column(u'transition', sa.Column('ip_address', sa.String(), nullable=True))
    op.drop_column(u'transition', 'ip_addres')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'transition', sa.Column('ip_addres', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column(u'transition', 'ip_address')
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.drop_column(u'purchase', 'cr_corporate_id')
    op.drop_constraint('corporate', 'account', type_='foreignkey')
    op.drop_column(u'account', 'cr_corporate_id')
    op.drop_column(u'account', 'badge_name')
    op.drop_table('corporate')
    ### end Alembic commands ###
