"""created buyer and purchase table

Revision ID: 5234df18599
Revises: 441179703573
Create Date: 2015-03-09 04:57:04.792967

"""

# revision identifiers, used by Alembic.
revision = '5234df18599'
down_revision = '441179703573'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('person', 'company', 'government', name='buyer_types'), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('document', sa.Text(), nullable=True),
    sa.Column('contact', sa.Text(), nullable=True),
    sa.Column('address_street', sa.Text(), nullable=True),
    sa.Column('address_number', sa.Text(), nullable=True),
    sa.Column('address_extra', sa.Text(), nullable=True),
    sa.Column('address_zipcode', sa.Text(), nullable=True),
    sa.Column('address_city', sa.Text(), nullable=True),
    sa.Column('address_country', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase')
    op.drop_table('buyer')
    ENUM(name="buyer_types").drop(op.get_bind(), checkfirst=False)
    ### end Alembic commands ###
