"""badge table is created

Revision ID: 5301d6bd6e81
Revises: 39a9a9acc78f
Create Date: 2015-07-03 15:01:42.098652

"""

# revision identifiers, used by Alembic.
revision = '5301d6bd6e81'
down_revision = '39a9a9acc78f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('issuer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('organization', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['issuer_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['purchase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('badge')
    ### end Alembic commands ###
