"""adding document column to visitor model

Revision ID: 561cf7c99269
Revises: 465d0dff297
Create Date: 2015-07-08 18:53:36.302485

"""

# revision identifiers, used by Alembic.
revision = '561cf7c99269'
down_revision = '465d0dff297'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitor', sa.Column('document', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visitor', 'document')
    ### end Alembic commands ###
