"""added proposal table

Revision ID: 564d391c174c
Revises: None
Create Date: 2015-01-07 18:26:25.697505

"""

# revision identifiers, used by Alembic.
revision = '564d391c174c'
down_revision = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects.postgresql import ENUM



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('full', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('level', sa.Enum('beginner', 'advanced', name='proposal_levels'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposal')
    ENUM(name="proposal_levels").drop(op.get_bind(), checkfirst=False)
    ### end Alembic commands ###
