"""added columns for boleto transition error and payment info

Revision ID: 5687e4a07500
Revises: 3c531310f2d0
Create Date: 2015-03-31 03:16:17.637662

"""

# revision identifiers, used by Alembic.
revision = '5687e4a07500'
down_revision = '3c531310f2d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transition', sa.Column('bo_errors', sa.Text(), nullable=True))
    op.add_column('transition', sa.Column('bo_paid_amount', sa.Numeric(), nullable=True))
    op.add_column('transition', sa.Column('bo_payment_date', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transition', 'bo_payment_date')
    op.drop_column('transition', 'bo_paid_amount')
    op.drop_column('transition', 'bo_errors')
    ### end Alembic commands ###
