"""adding document field (for CPF/passport)

Revision ID: 592d911e8679
Revises: 3629377a0cc2
Create Date: 2015-02-06 03:14:59.180240

"""

# revision identifiers, used by Alembic.
revision = '592d911e8679'
down_revision = '3629377a0cc2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('document', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'document')
    ### end Alembic commands ###
