"""cash related changes

Revision ID: 59de5bad6c5e
Revises: ff0cf6ed9d3
Create Date: 2015-06-30 20:48:55.826908

"""

# revision identifiers, used by Alembic.
revision = '59de5bad6c5e'
down_revision = 'ff0cf6ed9d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('can_pay_cash', sa.Boolean(), server_default='f', nullable=True))
    op.add_column('transition', sa.Column('cashier_id', sa.Integer(), nullable=True))
    op.add_column('transition', sa.Column('ip_addres', sa.String(), nullable=True))
    op.create_foreign_key(None, 'transition', 'account', ['cashier_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transition', type_='foreignkey')
    op.drop_column('transition', 'ip_addres')
    op.drop_column('transition', 'cashier_id')
    op.drop_column('product', 'can_pay_cash')
    ### end Alembic commands ###
