"""added corporate tables

Revision ID: 610662e5be4
Revises: 3f7a730da6dc
Create Date: 2015-04-22 07:50:15.667821

"""

# revision identifiers, used by Alembic.
revision = '610662e5be4'
down_revision = '3f7a730da6dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('document', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corporate_invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('corporate_id', sa.Integer(), nullable=True),
    sa.Column('recipient', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('document', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'cancelled', name='corporate_invite_statuses'), nullable=True),
    sa.ForeignKeyConstraint(['corporate_id'], ['corporate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'purchase', sa.Column('cr_corporate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase', 'corporate', ['cr_corporate_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.drop_column(u'purchase', 'cr_corporate_id')
    op.drop_table('corporate_invite')
    op.drop_table('corporate')
    ### end Alembic commands ###
