"""payment table

Revision ID: 622aeeebb80
Revises: 5234df18599
Create Date: 2015-03-13 01:28:05.724874

"""

# revision identifiers, used by Alembic.
revision = '622aeeebb80'
down_revision = '5234df18599'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=2), nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    ### end Alembic commands ###
