"""added_corporate_tables

Revision ID: a6d7678149d
Revises: 3f7a730da6dc
Create Date: 2015-05-06 06:03:27.507654

"""

# revision identifiers, used by Alembic.
revision = 'a6d7678149d'
down_revision = '3f7a730da6dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('document', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'account', sa.Column('cr_corporate_id', sa.Integer(), nullable=True))
    op.create_foreign_key('corporate', 'account', 'corporate', ['cr_corporate_id'], ['id'])
    op.add_column(u'purchase', sa.Column('cr_corporate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase', 'corporate', ['cr_corporate_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.drop_column(u'purchase', 'cr_corporate_id')
    op.drop_constraint('corporate', 'account', type_='foreignkey')
    op.drop_column(u'account', 'cr_corporate_id')
    op.drop_table('corporate')
    ### end Alembic commands ###
