"""certificate_name field for account

Revision ID: e95413a8654
Revises: 3fd61abd510d
Create Date: 2015-07-24 00:27:48.472718

"""

# revision identifiers, used by Alembic.
revision = 'e95413a8654'
down_revision = '3fd61abd510d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('certificate_name', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'certificate_name')
    ### end Alembic commands ###
