"""added_corporate_tables

Revision ID: f8e7dfe1520
Revises: 3f7a730da6dc
Create Date: 2015-04-27 00:17:05.730255

"""

# revision identifiers, used by Alembic.
revision = 'f8e7dfe1520'
down_revision = '3f7a730da6dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('document', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corporate_employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corporate_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('document', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corporate_id'], ['corporate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'purchase', sa.Column('cr_corporate_id', sa.Integer(), nullable=True))
    op.create_foreign_key('purchase_corporate_id_fkey', 'purchase', 'corporate', ['cr_corporate_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('purchase_corporate_id_fkey', 'purchase', type_='foreignkey')
    op.drop_column(u'purchase', 'cr_corporate_id')
    op.drop_table('corporate_employee')
    op.drop_table('corporate')
    ### end Alembic commands ###
