DEBUG = True
TESTING = False

SQLALCHEMY_POOL_SIZE = None
SQLALCHEMY_POOL_TIMEOUT = None
SQLALCHEMY_POOL_RECYCLE = None
SQLALCHEMY_DATABASE_URI = 'sqlite:////tmp/segue.db'

CORS_HEADERS = 'Content-Type,Authorization'
